'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace Exporter


	''' <summary>
	''' _Default class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class _Default

		''' <summary>
		''' Head1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ASPxRoundPanel1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxRoundPanel1 As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

		''' <summary>
		''' ASPxRadioButtonList1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxRadioButtonList1 As Global.DevExpress.Web.ASPxEditors.ASPxRadioButtonList

		''' <summary>
		''' ASPxRoundPanel2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxRoundPanel2 As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

		''' <summary>
		''' ASPxRadioButtonList2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxRadioButtonList2 As Global.DevExpress.Web.ASPxEditors.ASPxRadioButtonList

		''' <summary>
		''' ASPxButton1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxButton1 As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' ASPxButton2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxButton2 As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' ASPxButton3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxButton3 As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' ASPxGridView1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxGridView1 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' ASPxGridView2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxGridView2 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' dsCategories control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dsCategories As Global.System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' dsProduct control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dsProduct As Global.System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' ASPxGridViewExporter1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxGridViewExporter1 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
	End Class
End Namespace
